trigger:
  branches:
    include:
      - master

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-47P7H1A

variables:
  dockerRegistryServiceConnection: 'DockerHubConnection'
  imageRepository: 'ghofraneferchichi/configserv'
  tag: '$(Build.BuildId)'

steps:
  - task: Docker@2
    displayName: Build and Push Docker image
    inputs:
      command: buildAndPush
      dockerfile: '$(Build.SourcesDirectory)/config-server/Dockerfile'
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(imageRepository)'
      tags: $(tag)

  - script: |
      echo "Listing contents of $(Build.SourcesDirectory)/my-chart/templates"
      dir "$(Build.SourcesDirectory)/my-chart/templates"
    displayName: 'List Directory Contents'

  - task: PowerShell@2
    displayName: Update Deployment YAML for config-server
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Updating Deployment YAML file for config-server with new image tag"
        $yamlPath = "$(Build.SourcesDirectory)/my-chart/templates/config-server-deployment.yaml"
        Write-Host "YAML Path: $yamlPath"
        $content = Get-Content $yamlPath -Raw
        $content = $content -replace 'image: ghofraneferchichi/configserv:.+', "image: ghofraneferchichi/configserv:$(Build.BuildId)"
        $content | Set-Content $yamlPath

  - task: PowerShell@2
    displayName: Commit and push updated Deployment YAML files
    inputs:
      targetType: 'inline'
      script: |
        git config --global user.email "ghofranefer01@gmail.com"
        git config --global user.name "GhofraneFerchichi"
        cd "$(Build.SourcesDirectory)/my-chart/templates"
        git checkout master  # Ensure you are on the correct branch
        git pull origin master  # Pull latest changes
        # Use PowerShell to replace the image tag in the deployment.yaml file
        (Get-Content config-server-deployment.yaml) -replace 'image: ghofraneferchichi/configserv:.+', "image: ghofraneferchichi/configserv:$(Build.BuildId)" | Set-Content config-server-deployment.yaml
        git add config-server-deployment.yaml
        git commit -m "Update Docker image tag to $(Build.BuildId) in config-server deployment YAML file"
        git push origin master  # Push changes back to the repository
