trigger:
  branches:
    include:
      - master

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-47P7H1A

steps:
  - task: Docker@2
    displayName: Build Docker image
    inputs:
      command: build
      dockerfile: '$(Build.SourcesDirectory)/microservice-produits/Dockerfile'
      tags: |
        ghofraneferchichi/prodback:$(Build.BuildId)

  - script: |
      echo "Updating Deployment YAML file for microservice-produits with new image tag"
      sed -i 's/image: ghofraneferchichi\/prodback:.*/image: ghofraneferchichi\/prodback:$(Build.BuildId)/' $(Build.SourcesDirectory)/microservice-produits/deployment.yaml
    displayName: Update Deployment YAML for microservice-produits

  - task: Docker@2
    displayName: Push image to Docker Hub
    inputs:
      command: push
      containerRegistry: 'DockerHubConnection'
      repository: 'ghofraneferchichi/prodback'
      tags: $(Build.BuildId)

