trigger:
  branches:
    include:
      - master

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-47P7H1A

steps:
  - task: Docker@2
    displayName: Build Docker image
    inputs:
      command: build
      containerRegistry: 'DockerHubConnection'
      dockerfile: '$(Build.SourcesDirectory)/microservice-produits/Dockerfile'
      tags: |
        ghofraneferchichi/prodback:$(Build.BuildId)

  - task: Docker@2
    displayName: Push image to Docker Hub
    inputs:
      command: push
      containerRegistry: 'DockerHubConnection'
      repository: 'ghofraneferchichi/prodback'
      tags: $(Build.BuildId)

  - script: |
      echo "Updating Deployment YAML file for microservice-produits with new image tag"
      sed -i 's/image: ghofraneferchichi\/prodback:.*/image: ghofraneferchichi\/prodback:$(Build.BuildId)/' $(Build.SourcesDirectory)/microservice-produits/deployment.yaml
    displayName: Update Deployment YAML for microservice-produits

  - script: |
      git config --global user.email "ghofrane.ferchichi@esprit.tn"
      git config --global user.name "GhofraneFerchichi"
      cd $(Build.SourcesDirectory)
      git checkout -b update-image-tag
      git add microservice-produits/deployment.yaml
      git commit -m "Update Docker image tag to $(Build.BuildId) in deployment YAML files"
      git push origin update-image-tag
    displayName: Commit and push updated Deployment YAML files
