eureka:
  instance:
    hostname: 172.173.184.146
  client:
    serviceUrl:
      defaultZone: http://172.173.184.146:8761/eureka

server:
  port: 9009

spring:
  application:
    name: mcommandes
  config:
    import: optional:configserver:http://172.173.184.146:9012
    user-url: http://172.173.184.146:9010  # Define the user service URL here
    mproduits-url: http://172.173.184.146:9004  # Define the property here
    mpanier-url: http://172.173.184.146:9005

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.173.184.146:3306/db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        url: ${spring.config.user-url},${spring.config.mproduits-url},${spring.config.mpanier-url}
