eureka:
  instance:
    hostname: 10.0.41.57
  client:
    serviceUrl:
      defaultZone: http://10.0.41.57:8761/eureka

server:
  port: 9009

spring:
  application:
    name: mcommandes
  config:
    import: optional:configserver:http://10.0.138.22:9012
    user-url: http://10.0.75.250:9010  # Define the user service URL here
    mproduits-url: http://10.0.125.97:9004  # Define the property here

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.156.86:3306/db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        url: ${spring.config.user-url},${spring.config.mproduits-url}
