eureka:
  instance:
    hostname: 10.0.41.57
  client:
    serviceUrl:
      defaultZone: http://51.8.66.223:8761/eureka

server:
  port: 9009

spring:
  application:
    name: mcommandes
  config:
    import: optional:configserver:http://51.8.66.145:9012
    user-url: http://51.8.67.131:9010  # Define the user service URL here
    mproduits-url: http://51.8.66.238:9004  # Define the property here
    mpanier-url: http://51.8.67.167:9005

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://51.8.66.71:3306/db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        url: ${spring.config.user-url},${spring.config.mproduits-url},${application.config.mpanier-url}
