eureka:
  instance:
    hostname: 138.91.192.17  # Updated with the mcommandes external IP
  client:
    serviceUrl:
      defaultZone: http://104.210.36.100:8761/eureka  # Updated Eureka defaultZone

server:
  port: 9009

spring:
  application:
    name: mcommandes
  config:
    import: optional:configserver:http://138.91.194.193:9012  # Updated Config server IP address
    user-url: http://138.91.192.17:9010  # Updated user service URL
    mproduits-url: http://138.91.194.151:9004  # Updated mproduits service URL
    mpanier-url: http://104.210.32.234:9005  # Updated mpanier service URL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://104.210.40.63:3306/db?createDatabaseIfNotExist=true  # Updated MySQL server IP address
    username: root
    password: root  # Ensure the password is set correctly
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        url: ${spring.config.user-url},${spring.config.mproduits-url},${spring.config.mpanier-url}
