eureka:
  instance:
    hostname: 172.171.181.71  # Updated with the mcommandes external IP
  client:
    serviceUrl:
      defaultZone: http://51.8.67.177:8761/eureka  # Updated Eureka server IP address

server:
  port: 9009

spring:
  application:
    name: mcommandes
  config:
    import: optional:configserver:http://51.8.64.162:9012  # Updated Config server IP address
    user-url: http://172.171.180.147:9010  # Updated user-microservice IP address
    mproduits-url: http://172.171.182.34:9004  # Updated mproduits IP address
    mpanier-url: http://172.171.182.83:9005  # Updated mpanier IP address

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.171.180.232:3306/db?createDatabaseIfNotExist=true  # Updated MySQL server IP address
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        url: ${spring.config.user-url},${spring.config.mproduits-url},${spring.config.mpanier-url}
