spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://51.8.240.21:9012  # Updated Config server IP address
---
eureka:
  instance:
    hostname: 51.8.240.59  # Updated with the gateway external IP
  client:
    serviceUrl:
      defaultZone: http://51.8.240.64:8761/eureka  # Updated Eureka defaultZone

server:
  port: 8007

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mcommandes
          uri: lb://mcommandes  # Using service name instead of IP
          predicates:
            - Path=/api/v1/mcommandes/**
        - id: mpanier
          uri: lb://mpanier  # Using service name instead of IP
          predicates:
            - Path=/api/v1/mpanier/**
        - id: mproduits
          uri: lb://mproduits  # Using service name instead of IP
          predicates:
            - Path=/api/v1/mproduits/**

management:
  tracing:
    sampling:
      probability: 1.0
