eureka:
  instance:
    hostname: 104.210.44.173  # Updated with the user-microservice external IP
  client:
    serviceUrl:
      defaultZone: http://104.210.36.100:8761/eureka  # Updated Eureka defaultZone

server:
  port: 9010

spring:
  application:
    name: user-microservice
  cloud:
    config:
      import: optional:configserver:http://138.91.194.193:9012  # Updated Config server IP address
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://104.210.40.63:3306/db  # Updated MySQL server IP address
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true  # Enable bean definition overriding

# File upload settings
spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB

# Payment Stripe API
stripe.key.secret: sk_test_51HGXXNFZZEoYtESMGVTRVixCsC9oFknTb3oSaBjxB9oOETbDZAgeHvwcoSK3Qmg1RGjT2QuiLIiV3zF1XDkdoix300JyfSeCvJ

# JWT Configuration
spring.data.rest.base-path: /api
app.jwt.secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ikdob2ZyYW5lIEZlcmNoaWNoaSIsImlhdCI6MTUxNjIzOTAyMn0.JiGoQ2WGzlzlkTFzuajIvoSIJq2yHb4Tem-AOb1JkMw
app.jwt.expiration-in-ms: 86400000
authentication.internal-api-key: Internal!@
spring.main.allow-circular-references: true
spring.main.allow-bean-definition-overriding: true

allowed.origins: https://localhost:4200

# Email Configuration
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ghofrane.ferchichi@edu.isetcom.tn
  password: lmxehqljxgqqhmbv
  properties:
    mail.smtp.auth: true
    mail.smtp.connectiontimeout: 5000
    mail.smtp.timeout: 5000
    mail.smtp.writetimeout: 5000
    mail.smtp.starttls.enable: true
