eureka:
  instance:
    hostname: 172.171.180.147  # Updated with the user-microservice external IP
  client:
    serviceUrl:
      defaultZone: http://51.8.67.177:8761/eureka  # Updated Eureka defaultZone

server:
  port: 9010

spring:
  application:
    name: user-microservice
  cloud:
    config:
      import: optional:configserver:http://51.8.64.162:9012  # Updated Config server IP address
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.171.180.232:3306/db  # Updated MySQL server IP address
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

## File upload settings
spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB

## Payment Stripe API
stripe.key.secret: sk_test_51HGXXNFZZEoYtESMGVTRVixCsC9oFknTb3oSaBjxB9oOETbDZAgeHvwcoSK3Qmg1RGjT2QuiLIiV3zF1XDkdoix300JyfSeCvJ

## JWT Configuration
spring.data.rest.base-path: /api
app.jwt.secret: RandomSecretKeyRandomSecretKeyRandomSecretKeyRandomSecretKeyRandomSecretKeyRandomSecretKeyRandomSecretKeyRandomSecretKey
app.jwt.expiration-in-ms: 86400000
authentication.internal-api-key: Internal!@
spring.main.allow-circular-references: true
spring.main.allow-bean-definition-overriding: true

## Frontend Configuration
allowed.origins: *

## Email Configuration
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ghofrane.ferchichi@edu.isetcom.tn
  password: zzxvnoeavrsbsiwc

  properties:
    mail.smtp.auth: true
    mail.smtp.connectiontimeout: 5000
    mail.smtp.timeout: 5000
    mail.smtp.writetimeout: 5000
    mail.smtp.starttls.enable: true
