---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  config.yaml: |
    registries:
      docker.io:
        url: https://index.docker.io/v1/
        credentials: secret:argocd/dockerhub-cred
