apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    SET GLOBAL host_cache_size=0;
    # Add more initialization SQL statements if needed

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-config
data:
  application.yml: |
    eureka:
      instance:
        hostname: 51.8.66.223
      client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
          defaultZone: http://51.8.66.223:8761/eureka
    server:
      port: 8761
