apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: db
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ghofraneferchichi/config-server:latest
          ports:
            - containerPort: 9012
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          image: ghofraneferchichi/discovery:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url": "jdbc:mysql://mysql:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username": "root", "spring.datasource.password": "root", "spring.jpa.hibernate.ddl-auto": "update"}'
          ports:
            - containerPort: 8761
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ghofraneferchichi/gateway:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url": "jdbc:mysql://mysql:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username": "root", "spring.datasource.password": "root", "spring.jpa.hibernate.ddl-auto": "update"}'
          ports:
            - containerPort: 8007
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: ghofraneferchichi/musers:1.1
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url": "jdbc:mysql://mysql:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username": "root", "spring.datasource.password": "root", "spring.jpa.hibernate.ddl-auto": "update"}'
          ports:
            - containerPort: 9010
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcommandes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcommandes
  template:
    metadata:
      labels:
        app: mcommandes
    spec:
      containers:
        - name: mcommandes
          image: ghofraneferchichi/mcommandes:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url": "jdbc:mysql://mysql:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username": "root", "spring.datasource.password": "root", "spring.jpa.hibernate.ddl-auto": "update"}'
          ports:
            - containerPort: 9009
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpanier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpanier
  template:
    metadata:
      labels:
        app: mpanier
    spec:
      containers:
        - name: mpanier
          image: ghofraneferchichi/mpanier:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url": "jdbc:mysql://mysql:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username": "root", "spring.datasource.password": "root", "spring.jpa.hibernate.ddl-auto": "update"}'
          ports:
            - containerPort: 9005
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mproduits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mproduits
  template:
    metadata:
      labels:
        app: mproduits
    spec:
      containers:
        - name: mproduits
          image: ghofraneferchichi/mproduits:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url": "jdbc:mysql://mysql:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username": "root", "spring.datasource.password": "root", "spring.jpa.hibernate.ddl-auto": "update"}'
          ports:
            - containerPort: 9004
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghofraneferchichi/treefronthome:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url": "jdbc:mysql://mysql:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC", "spring.datasource.username":
          ports:
            - containerPort: 80
          imagePullPolicy: Always