apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120s"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_route"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /3306
            pathType: Prefix
            backend:
              service:
                name: mysql
                port:
                  number: 3306
          - path: /9012
            pathType: Prefix
            backend:
              service:
                name: config-server
                port:
                  number: 9012
          - path: /8761
            pathType: Prefix
            backend:
              service:
                name: discovery
                port:
                  number: 8761
          - path: /8007
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8007
          - path: /9010
            pathType: Prefix
            backend:
              service:
                name: user-microservice
                port:
                  number: 9010
          - path: /9009
            pathType: Prefix
            backend:
              service:
                name: commande-microservice
                port:
                  number: 9009
          - path: /9005
            pathType: Prefix
            backend:
              service:
                name: panier-microservice
                port:
                  number: 9005
          - path: /9004
            pathType: Prefix
            backend:
              service:
                name: produits-microservice
                port:
                  number: 9004
          - path: /80
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
