eureka:
  instance:
    hostname: 10.0.138.22
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://104.210.36.100:8761/eureka  # Updated Eureka server IP address
server:
  port: 8761
spring:
  config:
    import: optional:configserver:http://138.91.194.193:9012  # Updated Config server IP address
  application:
    name: discovery
