eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mcommandes
          uri: lb://commande-microservice   # Utilisation du nom du service au lieu de localhost
          predicates:
            - Path=/api/v1/mcommandes/**
        - id: mproduits
          uri: lb://produit-microservice   # Utilisation du nom du service au lieu de localhost
          predicates:
            - Path=/api/v1/mproduits/**
        - id: mpanier
          uri: lb://produit-microservice   # Utilisation du nom du service au lieu de localhost
          predicates:
            - Path=/api/v1/mpanier/**
        - id: user-microservice
          uri: lb://user-microservice   # Utilisation du nom du service au lieu de localhost
          predicates:
            - Path=/api/authentication/**, /user/**

management:
  tracing:
    sampling:
      probability: 1.0
