eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mcommandes
          uri: lb://commande-microservice   # Using service name instead of localhost
          predicates:
            - Path=/api/v1/mcommandes/**

management:
  tracing:
    sampling:
      probability: 1.0
