eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://104.210.36.100:8761/eureka  # Updated Eureka server IP address

server:
  port: 9005

spring:
  application:
    name: mpanier
  config:
    import: optional:configserver:http://138.91.194.193:9012  # Updated Config server IP address
    mproduits-url: http://138.91.194.151:9004  # Updated mproduits IP address
    user-url: http://138.91.192.17:9010
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://104.210.40.63:3306/db  # Updated MySQL server IP address
    username: root
    password: root  # Ensure the password is set correctly
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
