eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://172.173.184.146:8761/eureka  # Assuming the Eureka server is running on this address


server:
  port: 9005

spring:
  application:
    name: mpanier
  config:
    import: optional:configserver:http://172.173.184.146:9012  # Updated with the config server address
    mproduits-url: http://172.173.184.146:9004  # Updated with the cluster IP
    user-url: http://172.173.184.146:9010  # Updated with the cluster IP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.173.184.146:3306/db  # Updated with the cluster IP
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
