eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://104.210.36.100:8761/eureka  # Updated with new Eureka server address

server:
  port: 9010
spring:
  application:
    name: user-microservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://104.210.40.63:3306/db  # Updated with new MySQL server address
    username: root
    password: root  # Ensure the password is set correctly
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
