server:
  port: 9010

spring:
  application:
    name: user-microservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.156.86:3306/testuser  # Assuming MySQL is running on the IP address 10.0.156.86
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
