eureka:
  instance:
    hostname: 104.210.32.234  # Updated with the mpanier external IP
  client:
    serviceUrl:
      defaultZone: http://104.210.36.100:8761/eureka  # Updated Eureka defaultZone

server:
  port: 9005

spring:
  application:
    name: mpanier
  config:
    import: optional:configserver:http://138.91.194.193:9012  # Updated Config server IP address
    mproduits-url: http://138.91.194.151:9004  # Updated mproduits service URL
    user-url: http://104.210.44.173:9010  # Updated user service URL ip
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://104.210.40.63:3306/db?createDatabaseIfNotExist=true  # Updated MySQL server IP address
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        url: ${spring.config.mproduits-url},${spring.config.user-url}
