# Default values for your-chart-name.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

mysql:
  image: mysql:8.0
  database: db
  rootPassword: root

config-server:
  image: ghofraneferchichi/configserv
  port: 9012

discovery:
  image: ghofraneferchichi/discback
  port: 8761

gateway:
  image: ghofraneferchichi/gatewayback
  port: 8007

user-microservice:
  image: ghofraneferchichi/microuserr
  port: 9010

commande-microservice:
  image: ghofraneferchichi/microcommm
  port: 9009

panier-microservice:
  image: ghofraneferchichi/micropannc
  port: 9005

produits-microservice:
  image: ghofraneferchichi/prodback
  port: 9004
frontend:
  image: ghofraneferchichi/lastimage
  port: 80
