# Default values for your-chart-name.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

mysql:
  image: mysql:8.0
  database: db
  rootPassword: root

config-server:
  image: ghofraneferchichi/config
  port: 9012

discovery:
  image: ghofraneferchichi/disc
  port: 8761

gateway:
  image: ghofraneferchichi/gate
  port: 8007

user-microservice:
  image: ghofraneferchichi/user
  port: 9010

commande-microservice:
  image: ghofraneferchichi/comm
  port: 9009

panier-microservice:
  image: ghofraneferchichi/pan
  port: 9005

produits-microservice:
  image: ghofraneferchichi/prod
  port: 9004
frontend:
  image: ghofraneferchichi/imagetree
  port: 80
