eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8761
spring:
  config:
    import: optional:configserver:http://51.8.64.162:9012  # Updated Config server IP address
  application:
    name: discovery
