eureka:
  instance:
    hostname: 172.171.82.118  # Updated with the mproduits external IP
  client:
    serviceUrl:
      defaultZone: http://51.8.240.64:8761/eureka  # Updated Eureka defaultZone

server:
  port: 9004

spring:
  application:
    name: mproduits
  config:
    import: optional:configserver:http://51.8.240.21:9012  # Updated Config server IP address
    user-url: http://172.171.81.145:9010  # Updated user-microservice IP address
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.171.82.162:3306/db  # Updated MySQL server IP address
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  entity-scan:
    base-packages: com.example.mpanier.model, com.mproduits.model, com.example.mpanier.model.PanierProduct

feign:
  client:
    config:
      default:
        url: ${spring.config.user-url}

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB
