eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9004

spring:
  application:
    name: mproduits
  config:
    import: optional:configserver:http://localhost:9007
    user-url: http://localhost:9010 # Define the user service URL here
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  entity-scan:
    base-packages: com.example.mpanier.model, com.mproduits.model, com.example.mpanier.model.PanierProduct
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        url: ${spring.config.user-url}
